In [1]:
import pandas as pd

In [3]:
df = pd.read_csv('MANUFACTURING_ALL.csv')
df

,INDUSTRY_ID,NAME,ACTION_ID,NAME.1,QUARTER,YEAR,VALUE_IN_PERCENTAGES
0,301,Food and food products,10,Utilisation,4,2003,79.4
1,301,Food and food products,10,Utilisation,1,2004,79.5
2,301,Food and food products,10,Utilisation,2,2004,80.5
3,301,Food and food products,10,Utilisation,3,2004,81.2
4,301,Food and food products,10,Utilisation,4,2004,83.4
...,...,...,...,...,...,...,...
14303,399,Furniture and other manufacturing industries,25,Reason for under-utilisation: Other reasons,4,2020,6.1
14304,399,Furniture and other manufacturing industries,25,Reason for under-utilisation: Other reasons,1,2021,2.1
14305,399,Furniture and other manufacturing industries,25,Reason for under-utilisation: Other reasons,2,2021,2.5
14306,399,Furniture and other manufacturing industries,25,Reason for under-utilisation: Other reasons,3,2021,3.7
14307,399,Furniture and other manufacturing industries,25,Reason for under-utilisation: Other reasons,4,2021,3.4

In [4]:
df['NAME.1'].unique()

array(['Utilisation', 'Under-utilisation total',
       'Reason for under-utilisation: Raw materials',
       'Reason for under-utilisation: Skilled labour',
       'Reason for under-utilisation: Semi- and unskilled labour',
       'Reason for under-utilisation: Insufficient demand',
       'Reason for under-utilisation: Other reasons'], dtype=object)

In [7]:
df.dtypes

INDUSTRY_ID               int64
NAME                     object
ACTION_ID                 int64
NAME.1                   object
QUARTER                   int64
YEAR                      int64
VALUE_IN_PERCENTAGES    float64
dtype: object

In [8]:
utili = df[df['NAME.1'] == 'Utilisation']
under = df[df['NAME.1'] == 'Under-utilisation total']
raw = df[df['NAME.1'] == 'Reason for under-utilisation: Raw materials']
skilled = df[df['NAME.1'] == 'Reason for under-utilisation: Skilled labour']
semi = df[df['NAME.1'] == 'Reason for under-utilisation: Semi- and unskilled labour']
demand = df[df['NAME.1'] == 'Reason for under-utilisation: Insufficient demand']
other = df[df['NAME.1'] == 'Reason for under-utilisation: Other reasons']

In [26]:
utili

,INDUSTRY_ID,NAME,ACTION_ID,NAME.1,QUARTER,YEAR,VALUE_IN_PERCENTAGES
0,301,Food and food products,10,Utilisation,4,2003,79.4
1,301,Food and food products,10,Utilisation,1,2004,79.5
2,301,Food and food products,10,Utilisation,2,2004,80.5
3,301,Food and food products,10,Utilisation,3,2004,81.2
4,301,Food and food products,10,Utilisation,4,2004,83.4
...,...,...,...,...,...,...,...
13865,399,Furniture and other manufacturing industries,10,Utilisation,4,2020,66.2
13866,399,Furniture and other manufacturing industries,10,Utilisation,1,2021,74.6
13867,399,Furniture and other manufacturing industries,10,Utilisation,2,2021,77.2
13868,399,Furniture and other manufacturing industries,10,Utilisation,3,2021,82.7
13869,399,Furniture and other manufacturing industries,10,Utilisation,4,2021,81.7

In [28]:
uu = utili.merge(under, on=['NAME', 'QUARTER', 'YEAR'], how= 'left')
uu

,INDUSTRY_ID_x,NAME,ACTION_ID_x,NAME.1_x,QUARTER,YEAR,VALUE_IN_PERCENTAGES_x,INDUSTRY_ID_y,ACTION_ID_y,NAME.1_y,VALUE_IN_PERCENTAGES_y
0,301,Food and food products,10,Utilisation,4,2003,79.4,301,20,Under-utilisation total,20.6
1,301,Food and food products,10,Utilisation,1,2004,79.5,301,20,Under-utilisation total,20.5
2,301,Food and food products,10,Utilisation,2,2004,80.5,301,20,Under-utilisation total,19.5
3,301,Food and food products,10,Utilisation,3,2004,81.2,301,20,Under-utilisation total,18.8
4,301,Food and food products,10,Utilisation,4,2004,83.4,301,20,Under-utilisation total,16.6
...,...,...,...,...,...,...,...,...,...,...,...
2039,399,Furniture and other manufacturing industries,10,Utilisation,4,2020,66.2,399,20,Under-utilisation total,33.8
2040,399,Furniture and other manufacturing industries,10,Utilisation,1,2021,74.6,399,20,Under-utilisation total,25.4
2041,399,Furniture and other manufacturing industries,10,Utilisation,2,2021,77.2,399,20,Under-utilisation total,22.8
2042,399,Furniture and other manufacturing industries,10,Utilisation,3,2021,82.7,399,20,Under-utilisation total,17.3
2043,399,Furniture and other manufacturing industries,10,Utilisation,4,2021,81.7,399,20,Under-utilisation total,18.3

In [30]:
uur = uu.merge(raw, on=['NAME', 'QUARTER', 'YEAR'], how='left')
uur

,INDUSTRY_ID_x,NAME,ACTION_ID_x,NAME.1_x,QUARTER,YEAR,VALUE_IN_PERCENTAGES_x,INDUSTRY_ID_y,ACTION_ID_y,NAME.1_y,VALUE_IN_PERCENTAGES_y,INDUSTRY_ID,ACTION_ID,NAME.1,VALUE_IN_PERCENTAGES
0,301,Food and food products,10,Utilisation,4,2003,79.4,301,20,Under-utilisation total,20.6,301,21,Reason for under-utilisation: Raw materials,3.5
1,301,Food and food products,10,Utilisation,1,2004,79.5,301,20,Under-utilisation total,20.5,301,21,Reason for under-utilisation: Raw materials,4.6
2,301,Food and food products,10,Utilisation,2,2004,80.5,301,20,Under-utilisation total,19.5,301,21,Reason for under-utilisation: Raw materials,3.9
3,301,Food and food products,10,Utilisation,3,2004,81.2,301,20,Under-utilisation total,18.8,301,21,Reason for under-utilisation: Raw materials,3.3
4,301,Food and food products,10,Utilisation,4,2004,83.4,301,20,Under-utilisation total,16.6,301,21,Reason for under-utilisation: Raw materials,1.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2039,399,Furniture and other manufacturing industries,10,Utilisation,4,2020,66.2,399,20,Under-utilisation total,33.8,399,21,Reason for under-utilisation: Raw materials,6.0
2040,399,Furniture and other manufacturing industries,10,Utilisation,1,2021,74.6,399,20,Under-utilisation total,25.4,399,21,Reason for under-utilisation: Raw materials,2.3
2041,399,Furniture and other manufacturing industries,10,Utilisation,2,2021,77.2,399,20,Under-utilisation total,22.8,399,21,Reason for under-utilisation: Raw materials,2.2
2042,399,Furniture and other manufacturing industries,10,Utilisation,3,2021,82.7,399,20,Under-utilisation total,17.3,399,21,Reason for under-utilisation: Raw materials,2.1
2043,399,Furniture and other manufacturing industries,10,Utilisation,4,2021,81.7,399,20,Under-utilisation total,18.3,399,21,Reason for under-utilisation: Raw materials,1.6

In [31]:
uurs = uur.merge(skilled, how='left', on=['NAME', 'QUARTER', 'YEAR'])
uurs

,INDUSTRY_ID_x,NAME,ACTION_ID_x,NAME.1_x,QUARTER,YEAR,VALUE_IN_PERCENTAGES_x,INDUSTRY_ID_y,ACTION_ID_y,NAME.1_y,VALUE_IN_PERCENTAGES_y,INDUSTRY_ID_x,ACTION_ID_x,NAME.1_x,VALUE_IN_PERCENTAGES_x,INDUSTRY_ID_y,ACTION_ID_y,NAME.1_y,VALUE_IN_PERCENTAGES_y
0,301,Food and food products,10,Utilisation,4,2003,79.4,301,20,Under-utilisation total,20.6,301,21,Reason for under-utilisation: Raw materials,3.5,301,22,Reason for under-utilisation: Skilled labour,1.2
1,301,Food and food products,10,Utilisation,1,2004,79.5,301,20,Under-utilisation total,20.5,301,21,Reason for under-utilisation: Raw materials,4.6,301,22,Reason for under-utilisation: Skilled labour,1.3
2,301,Food and food products,10,Utilisation,2,2004,80.5,301,20,Under-utilisation total,19.5,301,21,Reason for under-utilisation: Raw materials,3.9,301,22,Reason for under-utilisation: Skilled labour,1.2
3,301,Food and food products,10,Utilisation,3,2004,81.2,301,20,Under-utilisation total,18.8,301,21,Reason for under-utilisation: Raw materials,3.3,301,22,Reason for under-utilisation: Skilled labour,1.4
4,301,Food and food products,10,Utilisation,4,2004,83.4,301,20,Under-utilisation total,16.6,301,21,Reason for under-utilisation: Raw materials,1.9,301,22,Reason for under-utilisation: Skilled labour,0.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2039,399,Furniture and other manufacturing industries,10,Utilisation,4,2020,66.2,399,20,Under-utilisation total,33.8,399,21,Reason for under-utilisation: Raw materials,6.0,399,22,Reason for under-utilisation: Skilled labour,0.7
2040,399,Furniture and other manufacturing industries,10,Utilisation,1,2021,74.6,399,20,Under-utilisation total,25.4,399,21,Reason for under-utilisation: Raw materials,2.3,399,22,Reason for under-utilisation: Skilled labour,0.8
2041,399,Furniture and other manufacturing industries,10,Utilisation,2,2021,77.2,399,20,Under-utilisation total,22.8,399,21,Reason for under-utilisation: Raw materials,2.2,399,22,Reason for under-utilisation: Skilled labour,0.4
2042,399,Furniture and other manufacturing industries,10,Utilisation,3,2021,82.7,399,20,Under-utilisation total,17.3,399,21,Reason for under-utilisation: Raw materials,2.1,399,22,Reason for under-utilisation: Skilled labour,0.4
2043,399,Furniture and other manufacturing industries,10,Utilisation,4,2021,81.7,399,20,Under-utilisation total,18.3,399,21,Reason for under-utilisation: Raw materials,1.6,399,22,Reason for under-utilisation: Skilled labour,0.4

In [32]:
uurss = uurs.merge(semi, how='left', on=['NAME', 'QUARTER', 'YEAR'])
uurss

,INDUSTRY_ID_x,NAME,ACTION_ID_x,NAME.1_x,QUARTER,YEAR,VALUE_IN_PERCENTAGES_x,INDUSTRY_ID_y,ACTION_ID_y,NAME.1_y,...,NAME.1_x,VALUE_IN_PERCENTAGES_x,INDUSTRY_ID_y,ACTION_ID_y,NAME.1_y,VALUE_IN_PERCENTAGES_y,INDUSTRY_ID,ACTION_ID,NAME.1,VALUE_IN_PERCENTAGES
0,301,Food and food products,10,Utilisation,4,2003,79.4,301,20,Under-utilisation total,...,Reason for under-utilisation: Raw materials,3.5,301,22,Reason for under-utilisation: Skilled labour,1.2,301,23,Reason for under-utilisation: Semi- and unskil...,0.1
1,301,Food and food products,10,Utilisation,1,2004,79.5,301,20,Under-utilisation total,...,Reason for under-utilisation: Raw materials,4.6,301,22,Reason for under-utilisation: Skilled labour,1.3,301,23,Reason for under-utilisation: Semi- and unskil...,0.1
2,301,Food and food products,10,Utilisation,2,2004,80.5,301,20,Under-utilisation total,...,Reason for under-utilisation: Raw materials,3.9,301,22,Reason for under-utilisation: Skilled labour,1.2,301,23,Reason for under-utilisation: Semi- and unskil...,0.1
3,301,Food and food products,10,Utilisation,3,2004,81.2,301,20,Under-utilisation total,...,Reason for under-utilisation: Raw materials,3.3,301,22,Reason for under-utilisation: Skilled labour,1.4,301,23,Reason for under-utilisation: Semi- and unskil...,0.4
4,301,Food and food products,10,Utilisation,4,2004,83.4,301,20,Under-utilisation total,...,Reason for under-utilisation: Raw materials,1.9,301,22,Reason for under-utilisation: Skilled labour,0.8,301,23,Reason for under-utilisation: Semi- and unskil...,0.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2039,399,Furniture and other manufacturing industries,10,Utilisation,4,2020,66.2,399,20,Under-utilisation total,...,Reason for under-utilisation: Raw materials,6.0,399,22,Reason for under-utilisation: Skilled labour,0.7,399,23,Reason for under-utilisation: Semi- and unskil...,0.2
2040,399,Furniture and other manufacturing industries,10,Utilisation,1,2021,74.6,399,20,Under-utilisation total,...,Reason for under-utilisation: Raw materials,2.3,399,22,Reason for under-utilisation: Skilled labour,0.8,399,23,Reason for under-utilisation: Semi- and unskil...,0.6
2041,399,Furniture and other manufacturing industries,10,Utilisation,2,2021,77.2,399,20,Under-utilisation total,...,Reason for under-utilisation: Raw materials,2.2,399,22,Reason for under-utilisation: Skilled labour,0.4,399,23,Reason for under-utilisation: Semi- and unskil...,0.6
2042,399,Furniture and other manufacturing industries,10,Utilisation,3,2021,82.7,399,20,Under-utilisation total,...,Reason for under-utilisation: Raw materials,2.1,399,22,Reason for under-utilisation: Skilled labour,0.4,399,23,Reason for under-utilisation: Semi- and unskil...,0.2
2043,399,Furniture and other manufacturing industries,10,Utilisation,4,2021,81.7,399,20,Under-utilisation total,...,Reason for under-utilisation: Raw materials,1.6,399,22,Reason for under-utilisation: Skilled labour,0.4,399,23,Reason for under-utilisation: Semi- and unskil...,0.5

In [33]:
uurssd = uurss.merge(demand, how='left', on=['NAME', 'QUARTER', 'YEAR'])
uurssd

,INDUSTRY_ID_x,NAME,ACTION_ID_x,NAME.1_x,QUARTER,YEAR,VALUE_IN_PERCENTAGES_x,INDUSTRY_ID_y,ACTION_ID_y,NAME.1_y,...,NAME.1_y,VALUE_IN_PERCENTAGES_y,INDUSTRY_ID_x,ACTION_ID_x,NAME.1_x,VALUE_IN_PERCENTAGES_x,INDUSTRY_ID_y,ACTION_ID_y,NAME.1_y,VALUE_IN_PERCENTAGES_y
0,301,Food and food products,10,Utilisation,4,2003,79.4,301,20,Under-utilisation total,...,Reason for under-utilisation: Skilled labour,1.2,301,23,Reason for under-utilisation: Semi- and unskil...,0.1,301,24,Reason for under-utilisation: Insufficient demand,13.2
1,301,Food and food products,10,Utilisation,1,2004,79.5,301,20,Under-utilisation total,...,Reason for under-utilisation: Skilled labour,1.3,301,23,Reason for under-utilisation: Semi- and unskil...,0.1,301,24,Reason for under-utilisation: Insufficient demand,11.8
2,301,Food and food products,10,Utilisation,2,2004,80.5,301,20,Under-utilisation total,...,Reason for under-utilisation: Skilled labour,1.2,301,23,Reason for under-utilisation: Semi- and unskil...,0.1,301,24,Reason for under-utilisation: Insufficient demand,12.0
3,301,Food and food products,10,Utilisation,3,2004,81.2,301,20,Under-utilisation total,...,Reason for under-utilisation: Skilled labour,1.4,301,23,Reason for under-utilisation: Semi- and unskil...,0.4,301,24,Reason for under-utilisation: Insufficient demand,11.7
4,301,Food and food products,10,Utilisation,4,2004,83.4,301,20,Under-utilisation total,...,Reason for under-utilisation: Skilled labour,0.8,301,23,Reason for under-utilisation: Semi- and unskil...,0.9,301,24,Reason for under-utilisation: Insufficient demand,11.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2039,399,Furniture and other manufacturing industries,10,Utilisation,4,2020,66.2,399,20,Under-utilisation total,...,Reason for under-utilisation: Skilled labour,0.7,399,23,Reason for under-utilisation: Semi- and unskil...,0.2,399,24,Reason for under-utilisation: Insufficient demand,20.8
2040,399,Furniture and other manufacturing industries,10,Utilisation,1,2021,74.6,399,20,Under-utilisation total,...,Reason for under-utilisation: Skilled labour,0.8,399,23,Reason for under-utilisation: Semi- and unskil...,0.6,399,24,Reason for under-utilisation: Insufficient demand,19.6
2041,399,Furniture and other manufacturing industries,10,Utilisation,2,2021,77.2,399,20,Under-utilisation total,...,Reason for under-utilisation: Skilled labour,0.4,399,23,Reason for under-utilisation: Semi- and unskil...,0.6,399,24,Reason for under-utilisation: Insufficient demand,17.1
2042,399,Furniture and other manufacturing industries,10,Utilisation,3,2021,82.7,399,20,Under-utilisation total,...,Reason for under-utilisation: Skilled labour,0.4,399,23,Reason for under-utilisation: Semi- and unskil...,0.2,399,24,Reason for under-utilisation: Insufficient demand,10.9
2043,399,Furniture and other manufacturing industries,10,Utilisation,4,2021,81.7,399,20,Under-utilisation total,...,Reason for under-utilisation: Skilled labour,0.4,399,23,Reason for under-utilisation: Semi- and unskil...,0.5,399,24,Reason for under-utilisation: Insufficient demand,12.4

In [34]:
uurssdo = uurssd.merge(other,  how='left', on=['NAME', 'QUARTER', 'YEAR'])
uurssdo

,INDUSTRY_ID_x,NAME,ACTION_ID_x,NAME.1_x,QUARTER,YEAR,VALUE_IN_PERCENTAGES_x,INDUSTRY_ID_y,ACTION_ID_y,NAME.1_y,...,NAME.1_x,VALUE_IN_PERCENTAGES_x,INDUSTRY_ID_y,ACTION_ID_y,NAME.1_y,VALUE_IN_PERCENTAGES_y,INDUSTRY_ID,ACTION_ID,NAME.1,VALUE_IN_PERCENTAGES
0,301,Food and food products,10,Utilisation,4,2003,79.4,301,20,Under-utilisation total,...,Reason for under-utilisation: Semi- and unskil...,0.1,301,24,Reason for under-utilisation: Insufficient demand,13.2,301,25,Reason for under-utilisation: Other reasons,2.6
1,301,Food and food products,10,Utilisation,1,2004,79.5,301,20,Under-utilisation total,...,Reason for under-utilisation: Semi- and unskil...,0.1,301,24,Reason for under-utilisation: Insufficient demand,11.8,301,25,Reason for under-utilisation: Other reasons,2.7
2,301,Food and food products,10,Utilisation,2,2004,80.5,301,20,Under-utilisation total,...,Reason for under-utilisation: Semi- and unskil...,0.1,301,24,Reason for under-utilisation: Insufficient demand,12.0,301,25,Reason for under-utilisation: Other reasons,2.3
3,301,Food and food products,10,Utilisation,3,2004,81.2,301,20,Under-utilisation total,...,Reason for under-utilisation: Semi- and unskil...,0.4,301,24,Reason for under-utilisation: Insufficient demand,11.7,301,25,Reason for under-utilisation: Other reasons,2.0
4,301,Food and food products,10,Utilisation,4,2004,83.4,301,20,Under-utilisation total,...,Reason for under-utilisation: Semi- and unskil...,0.9,301,24,Reason for under-utilisation: Insufficient demand,11.5,301,25,Reason for under-utilisation: Other reasons,1.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2039,399,Furniture and other manufacturing industries,10,Utilisation,4,2020,66.2,399,20,Under-utilisation total,...,Reason for under-utilisation: Semi- and unskil...,0.2,399,24,Reason for under-utilisation: Insufficient demand,20.8,399,25,Reason for under-utilisation: Other reasons,6.1
2040,399,Furniture and other manufacturing industries,10,Utilisation,1,2021,74.6,399,20,Under-utilisation total,...,Reason for under-utilisation: Semi- and unskil...,0.6,399,24,Reason for under-utilisation: Insufficient demand,19.6,399,25,Reason for under-utilisation: Other reasons,2.1
2041,399,Furniture and other manufacturing industries,10,Utilisation,2,2021,77.2,399,20,Under-utilisation total,...,Reason for under-utilisation: Semi- and unskil...,0.6,399,24,Reason for under-utilisation: Insufficient demand,17.1,399,25,Reason for under-utilisation: Other reasons,2.5
2042,399,Furniture and other manufacturing industries,10,Utilisation,3,2021,82.7,399,20,Under-utilisation total,...,Reason for under-utilisation: Semi- and unskil...,0.2,399,24,Reason for under-utilisation: Insufficient demand,10.9,399,25,Reason for under-utilisation: Other reasons,3.7
2043,399,Furniture and other manufacturing industries,10,Utilisation,4,2021,81.7,399,20,Under-utilisation total,...,Reason for under-utilisation: Semi- and unskil...,0.5,399,24,Reason for under-utilisation: Insufficient demand,12.4,399,25,Reason for under-utilisation: Other reasons,3.4

In [35]:
merged = uurssdo.copy()
merged

,INDUSTRY_ID_x,NAME,ACTION_ID_x,NAME.1_x,QUARTER,YEAR,VALUE_IN_PERCENTAGES_x,INDUSTRY_ID_y,ACTION_ID_y,NAME.1_y,...,NAME.1_x,VALUE_IN_PERCENTAGES_x,INDUSTRY_ID_y,ACTION_ID_y,NAME.1_y,VALUE_IN_PERCENTAGES_y,INDUSTRY_ID,ACTION_ID,NAME.1,VALUE_IN_PERCENTAGES
0,301,Food and food products,10,Utilisation,4,2003,79.4,301,20,Under-utilisation total,...,Reason for under-utilisation: Semi- and unskil...,0.1,301,24,Reason for under-utilisation: Insufficient demand,13.2,301,25,Reason for under-utilisation: Other reasons,2.6
1,301,Food and food products,10,Utilisation,1,2004,79.5,301,20,Under-utilisation total,...,Reason for under-utilisation: Semi- and unskil...,0.1,301,24,Reason for under-utilisation: Insufficient demand,11.8,301,25,Reason for under-utilisation: Other reasons,2.7
2,301,Food and food products,10,Utilisation,2,2004,80.5,301,20,Under-utilisation total,...,Reason for under-utilisation: Semi- and unskil...,0.1,301,24,Reason for under-utilisation: Insufficient demand,12.0,301,25,Reason for under-utilisation: Other reasons,2.3
3,301,Food and food products,10,Utilisation,3,2004,81.2,301,20,Under-utilisation total,...,Reason for under-utilisation: Semi- and unskil...,0.4,301,24,Reason for under-utilisation: Insufficient demand,11.7,301,25,Reason for under-utilisation: Other reasons,2.0
4,301,Food and food products,10,Utilisation,4,2004,83.4,301,20,Under-utilisation total,...,Reason for under-utilisation: Semi- and unskil...,0.9,301,24,Reason for under-utilisation: Insufficient demand,11.5,301,25,Reason for under-utilisation: Other reasons,1.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2039,399,Furniture and other manufacturing industries,10,Utilisation,4,2020,66.2,399,20,Under-utilisation total,...,Reason for under-utilisation: Semi- and unskil...,0.2,399,24,Reason for under-utilisation: Insufficient demand,20.8,399,25,Reason for under-utilisation: Other reasons,6.1
2040,399,Furniture and other manufacturing industries,10,Utilisation,1,2021,74.6,399,20,Under-utilisation total,...,Reason for under-utilisation: Semi- and unskil...,0.6,399,24,Reason for under-utilisation: Insufficient demand,19.6,399,25,Reason for under-utilisation: Other reasons,2.1
2041,399,Furniture and other manufacturing industries,10,Utilisation,2,2021,77.2,399,20,Under-utilisation total,...,Reason for under-utilisation: Semi- and unskil...,0.6,399,24,Reason for under-utilisation: Insufficient demand,17.1,399,25,Reason for under-utilisation: Other reasons,2.5
2042,399,Furniture and other manufacturing industries,10,Utilisation,3,2021,82.7,399,20,Under-utilisation total,...,Reason for under-utilisation: Semi- and unskil...,0.2,399,24,Reason for under-utilisation: Insufficient demand,10.9,399,25,Reason for under-utilisation: Other reasons,3.7
2043,399,Furniture and other manufacturing industries,10,Utilisation,4,2021,81.7,399,20,Under-utilisation total,...,Reason for under-utilisation: Semi- and unskil...,0.5,399,24,Reason for under-utilisation: Insufficient demand,12.4,399,25,Reason for under-utilisation: Other reasons,3.4

In [36]:
merged.columns

Index(['INDUSTRY_ID_x', 'NAME', 'ACTION_ID_x', 'NAME.1_x', 'QUARTER', 'YEAR',
       'VALUE_IN_PERCENTAGES_x', 'INDUSTRY_ID_y', 'ACTION_ID_y', 'NAME.1_y',
       'VALUE_IN_PERCENTAGES_y', 'INDUSTRY_ID_x', 'ACTION_ID_x', 'NAME.1_x',
       'VALUE_IN_PERCENTAGES_x', 'INDUSTRY_ID_y', 'ACTION_ID_y', 'NAME.1_y',
       'VALUE_IN_PERCENTAGES_y', 'INDUSTRY_ID_x', 'ACTION_ID_x', 'NAME.1_x',
       'VALUE_IN_PERCENTAGES_x', 'INDUSTRY_ID_y', 'ACTION_ID_y', 'NAME.1_y',
       'VALUE_IN_PERCENTAGES_y', 'INDUSTRY_ID', 'ACTION_ID', 'NAME.1',
       'VALUE_IN_PERCENTAGES'],
      dtype='object')

# extracting wanted columns
## 1,4,5,6,10,14,18,22,26,30

In [37]:
 sep = merged.iloc[:, [1,4,5,6,10,14,18,22,26,30]]
sep

,NAME,QUARTER,YEAR,VALUE_IN_PERCENTAGES_x,VALUE_IN_PERCENTAGES_y,VALUE_IN_PERCENTAGES_x,VALUE_IN_PERCENTAGES_y,VALUE_IN_PERCENTAGES_x,VALUE_IN_PERCENTAGES_y,VALUE_IN_PERCENTAGES
0,Food and food products,4,2003,79.4,20.6,3.5,1.2,0.1,13.2,2.6
1,Food and food products,1,2004,79.5,20.5,4.6,1.3,0.1,11.8,2.7
2,Food and food products,2,2004,80.5,19.5,3.9,1.2,0.1,12.0,2.3
3,Food and food products,3,2004,81.2,18.8,3.3,1.4,0.4,11.7,2.0
4,Food and food products,4,2004,83.4,16.6,1.9,0.8,0.9,11.5,1.5
...,...,...,...,...,...,...,...,...,...,...
2039,Furniture and other manufacturing industries,4,2020,66.2,33.8,6.0,0.7,0.2,20.8,6.1
2040,Furniture and other manufacturing industries,1,2021,74.6,25.4,2.3,0.8,0.6,19.6,2.1
2041,Furniture and other manufacturing industries,2,2021,77.2,22.8,2.2,0.4,0.6,17.1,2.5
2042,Furniture and other manufacturing industries,3,2021,82.7,17.3,2.1,0.4,0.2,10.9,3.7
2043,Furniture and other manufacturing industries,4,2021,81.7,18.3,1.6,0.4,0.5,12.4,3.4

In [48]:
sep['INDUSTRY'] = sep.iloc[:, 0]
sep

C:\Users\Tlou Ramotshela\anaconda3\lib\site-packages\pandas\core\indexing.py:1596: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[key] = _infer_fill_value(value)
C:\Users\Tlou Ramotshela\anaconda3\lib\site-packages\pandas\core\indexing.py:1765: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)

,NAME,QUARTER,YEAR,VALUE_IN_PERCENTAGES_x,VALUE_IN_PERCENTAGES_y,VALUE_IN_PERCENTAGES_x,VALUE_IN_PERCENTAGES_y,VALUE_IN_PERCENTAGES_x,VALUE_IN_PERCENTAGES_y,VALUE_IN_PERCENTAGES,INDUSTRY,0
0,INDUSTRY,4,2003,79.4,20.6,3.5,1.2,0.1,13.2,2.6,Food and food products,INDUSTRY
1,INDUSTRY,1,2004,79.5,20.5,4.6,1.3,0.1,11.8,2.7,Food and food products,INDUSTRY
2,INDUSTRY,2,2004,80.5,19.5,3.9,1.2,0.1,12.0,2.3,Food and food products,INDUSTRY
3,INDUSTRY,3,2004,81.2,18.8,3.3,1.4,0.4,11.7,2.0,Food and food products,INDUSTRY
4,INDUSTRY,4,2004,83.4,16.6,1.9,0.8,0.9,11.5,1.5,Food and food products,INDUSTRY
...,...,...,...,...,...,...,...,...,...,...,...,...
2039,INDUSTRY,4,2020,66.2,33.8,6.0,0.7,0.2,20.8,6.1,Furniture and other manufacturing industries,INDUSTRY
2040,INDUSTRY,1,2021,74.6,25.4,2.3,0.8,0.6,19.6,2.1,Furniture and other manufacturing industries,INDUSTRY
2041,INDUSTRY,2,2021,77.2,22.8,2.2,0.4,0.6,17.1,2.5,Furniture and other manufacturing industries,INDUSTRY
2042,INDUSTRY,3,2021,82.7,17.3,2.1,0.4,0.2,10.9,3.7,Furniture and other manufacturing industries,INDUSTRY
2043,INDUSTRY,4,2021,81.7,18.3,1.6,0.4,0.5,12.4,3.4,Furniture and other manufacturing industries,INDUSTRY

In [50]:
sep.columns

Index([                  'NAME',                'QUARTER',
                         'YEAR', 'VALUE_IN_PERCENTAGES_x',
       'VALUE_IN_PERCENTAGES_y', 'VALUE_IN_PERCENTAGES_x',
       'VALUE_IN_PERCENTAGES_y', 'VALUE_IN_PERCENTAGES_x',
       'VALUE_IN_PERCENTAGES_y',   'VALUE_IN_PERCENTAGES',
                     'INDUSTRY',                        0],
      dtype='object')

In [52]:
sep['UTILISATION'] = sep.iloc[:, 3]
sep['UNDER_UTILISATION'] = sep.iloc[:,4]
sep['RAW_MATERIALS'] = sep.iloc[:,5]
sep['SKILLED_LABOUR'] = sep.iloc[:,6]
sep['SEMI_AND_UNSKILLED LABOUR'] = sep.iloc[:,7]
sep['INSUFFICIENT_DEMAND'] = sep.iloc[:,8]
sep['OTHER_REASONS'] = sep.iloc[:,9]
sep

<ipython-input-52-cbdb640233c5>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sep['UTILISATION'] = sep.iloc[:, 3]
<ipython-input-52-cbdb640233c5>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sep['UNDER_UTILISATION'] = sep.iloc[:,4]
<ipython-input-52-cbdb640233c5>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sep['RAW_MATERIALS'] = sep.iloc[:,5]
<ipython-input-52-cbdb640233c5>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sep['SKILLED_LABOUR'] = sep.iloc[:,6]
<ipython-input-52-cbdb640233c5>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sep['SEMI_AND_UNSKILLED LABOUR'] = sep.iloc[:,7]
<ipython-input-52-cbdb640233c5>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sep['INSUFFICIENT_DEMAND'] = sep.iloc[:,8]
<ipython-input-52-cbdb640233c5>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sep['OTHER_REASONS'] = sep.iloc[:,9]

,NAME,QUARTER,YEAR,VALUE_IN_PERCENTAGES_x,VALUE_IN_PERCENTAGES_y,VALUE_IN_PERCENTAGES_x,VALUE_IN_PERCENTAGES_y,VALUE_IN_PERCENTAGES_x,VALUE_IN_PERCENTAGES_y,VALUE_IN_PERCENTAGES,INDUSTRY,0,UTILISATION,UNDER_UTILISATION,RAW_MATERIALS,SKILLED_LABOUR,SEMI_AND_UNSKILLED LABOUR,INSUFFICIENT_DEMAND,OTHER_REASONS
0,INDUSTRY,4,2003,79.4,20.6,3.5,1.2,0.1,13.2,2.6,Food and food products,INDUSTRY,79.4,20.6,3.5,1.2,0.1,13.2,2.6
1,INDUSTRY,1,2004,79.5,20.5,4.6,1.3,0.1,11.8,2.7,Food and food products,INDUSTRY,79.5,20.5,4.6,1.3,0.1,11.8,2.7
2,INDUSTRY,2,2004,80.5,19.5,3.9,1.2,0.1,12.0,2.3,Food and food products,INDUSTRY,80.5,19.5,3.9,1.2,0.1,12.0,2.3
3,INDUSTRY,3,2004,81.2,18.8,3.3,1.4,0.4,11.7,2.0,Food and food products,INDUSTRY,81.2,18.8,3.3,1.4,0.4,11.7,2.0
4,INDUSTRY,4,2004,83.4,16.6,1.9,0.8,0.9,11.5,1.5,Food and food products,INDUSTRY,83.4,16.6,1.9,0.8,0.9,11.5,1.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2039,INDUSTRY,4,2020,66.2,33.8,6.0,0.7,0.2,20.8,6.1,Furniture and other manufacturing industries,INDUSTRY,66.2,33.8,6.0,0.7,0.2,20.8,6.1
2040,INDUSTRY,1,2021,74.6,25.4,2.3,0.8,0.6,19.6,2.1,Furniture and other manufacturing industries,INDUSTRY,74.6,25.4,2.3,0.8,0.6,19.6,2.1
2041,INDUSTRY,2,2021,77.2,22.8,2.2,0.4,0.6,17.1,2.5,Furniture and other manufacturing industries,INDUSTRY,77.2,22.8,2.2,0.4,0.6,17.1,2.5
2042,INDUSTRY,3,2021,82.7,17.3,2.1,0.4,0.2,10.9,3.7,Furniture and other manufacturing industries,INDUSTRY,82.7,17.3,2.1,0.4,0.2,10.9,3.7
2043,INDUSTRY,4,2021,81.7,18.3,1.6,0.4,0.5,12.4,3.4,Furniture and other manufacturing industries,INDUSTRY,81.7,18.3,1.6,0.4,0.5,12.4,3.4

In [53]:
sep.columns

Index([                     'NAME',                   'QUARTER',
                            'YEAR',    'VALUE_IN_PERCENTAGES_x',
          'VALUE_IN_PERCENTAGES_y',    'VALUE_IN_PERCENTAGES_x',
          'VALUE_IN_PERCENTAGES_y',    'VALUE_IN_PERCENTAGES_x',
          'VALUE_IN_PERCENTAGES_y',      'VALUE_IN_PERCENTAGES',
                        'INDUSTRY',                           0,
                     'UTILISATION',         'UNDER_UTILISATION',
                   'RAW_MATERIALS',            'SKILLED_LABOUR',
       'SEMI_AND_UNSKILLED LABOUR',       'INSUFFICIENT_DEMAND',
                   'OTHER_REASONS'],
      dtype='object')

In [55]:
new_data = sep.iloc[:, [10, 1,2,12,13,14,15,16,17,18]]
new_data

,INDUSTRY,QUARTER,YEAR,UTILISATION,UNDER_UTILISATION,RAW_MATERIALS,SKILLED_LABOUR,SEMI_AND_UNSKILLED LABOUR,INSUFFICIENT_DEMAND,OTHER_REASONS
0,Food and food products,4,2003,79.4,20.6,3.5,1.2,0.1,13.2,2.6
1,Food and food products,1,2004,79.5,20.5,4.6,1.3,0.1,11.8,2.7
2,Food and food products,2,2004,80.5,19.5,3.9,1.2,0.1,12.0,2.3
3,Food and food products,3,2004,81.2,18.8,3.3,1.4,0.4,11.7,2.0
4,Food and food products,4,2004,83.4,16.6,1.9,0.8,0.9,11.5,1.5
...,...,...,...,...,...,...,...,...,...,...
2039,Furniture and other manufacturing industries,4,2020,66.2,33.8,6.0,0.7,0.2,20.8,6.1
2040,Furniture and other manufacturing industries,1,2021,74.6,25.4,2.3,0.8,0.6,19.6,2.1
2041,Furniture and other manufacturing industries,2,2021,77.2,22.8,2.2,0.4,0.6,17.1,2.5
2042,Furniture and other manufacturing industries,3,2021,82.7,17.3,2.1,0.4,0.2,10.9,3.7
2043,Furniture and other manufacturing industries,4,2021,81.7,18.3,1.6,0.4,0.5,12.4,3.4

In [56]:
new_data.dtypes

INDUSTRY                      object
QUARTER                        int64
YEAR                           int64
UTILISATION                  float64
UNDER_UTILISATION            float64
RAW_MATERIALS                float64
SKILLED_LABOUR               float64
SEMI_AND_UNSKILLED LABOUR    float64
INSUFFICIENT_DEMAND          float64
OTHER_REASONS                float64
dtype: object

In [66]:
# new_data['RAW_MATERIAL_%'] = new_data['RAW_MATERIALS']/new_data['UNDER_UTILISATION']*100
new_data['SKILLED_LABOUR_%'] = new_data['SKILLED_LABOUR']/new_data['UNDER_UTILISATION']*100
new_data['SEMI_AND_UNSKILLED LABOUR_%'] = new_data['SEMI_AND_UNSKILLED LABOUR']/new_data['UNDER_UTILISATION']*100
new_data['INSUFFICIENT_DEMAND_%'] = new_data['INSUFFICIENT_DEMAND']/new_data['UNDER_UTILISATION']*100
new_data['OTHER_REASONS_%'] = new_data['OTHER_REASONS']/new_data['UNDER_UTILISATION']*100
new_data

<ipython-input-66-4be91af8f67e>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_data['SKILLED_LABOUR_%'] = new_data['SKILLED_LABOUR']/new_data['UNDER_UTILISATION']*100
<ipython-input-66-4be91af8f67e>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_data['SEMI_AND_UNSKILLED LABOUR_%'] = new_data['SEMI_AND_UNSKILLED LABOUR']/new_data['UNDER_UTILISATION']*100
<ipython-input-66-4be91af8f67e>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_data['INSUFFICIENT_DEMAND_%'] = new_data['INSUFFICIENT_DEMAND']/new_data['UNDER_UTILISATION']*100
<ipython-input-66-4be91af8f67e>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_data['OTHER_REASONS_%'] = new_data['OTHER_REASONS']/new_data['UNDER_UTILISATION']*100

,INDUSTRY,QUARTER,YEAR,UTILISATION,UNDER_UTILISATION,RAW_MATERIALS,SKILLED_LABOUR,SEMI_AND_UNSKILLED LABOUR,INSUFFICIENT_DEMAND,OTHER_REASONS,RAW_MATERIAL_%,SKILLED_LABOUR_%,SEMI_AND_UNSKILLED LABOUR_%,INSUFFICIENT_DEMAND_%,OTHER_REASONS_%
0,Food and food products,4,2003,79.4,20.6,3.5,1.2,0.1,13.2,2.6,16.990291,5.825243,0.485437,64.077670,12.621359
1,Food and food products,1,2004,79.5,20.5,4.6,1.3,0.1,11.8,2.7,22.439024,6.341463,0.487805,57.560976,13.170732
2,Food and food products,2,2004,80.5,19.5,3.9,1.2,0.1,12.0,2.3,20.000000,6.153846,0.512821,61.538462,11.794872
3,Food and food products,3,2004,81.2,18.8,3.3,1.4,0.4,11.7,2.0,17.553191,7.446809,2.127660,62.234043,10.638298
4,Food and food products,4,2004,83.4,16.6,1.9,0.8,0.9,11.5,1.5,11.445783,4.819277,5.421687,69.277108,9.036145
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2039,Furniture and other manufacturing industries,4,2020,66.2,33.8,6.0,0.7,0.2,20.8,6.1,17.751479,2.071006,0.591716,61.538462,18.047337
2040,Furniture and other manufacturing industries,1,2021,74.6,25.4,2.3,0.8,0.6,19.6,2.1,9.055118,3.149606,2.362205,77.165354,8.267717
2041,Furniture and other manufacturing industries,2,2021,77.2,22.8,2.2,0.4,0.6,17.1,2.5,9.649123,1.754386,2.631579,75.000000,10.964912
2042,Furniture and other manufacturing industries,3,2021,82.7,17.3,2.1,0.4,0.2,10.9,3.7,12.138728,2.312139,1.156069,63.005780,21.387283
2043,Furniture and other manufacturing industries,4,2021,81.7,18.3,1.6,0.4,0.5,12.4,3.4,8.743169,2.185792,2.732240,67.759563,18.579235

In [67]:
new_data.columns

Index(['INDUSTRY', 'QUARTER', 'YEAR', 'UTILISATION', 'UNDER_UTILISATION',
       'RAW_MATERIALS', 'SKILLED_LABOUR', 'SEMI_AND_UNSKILLED LABOUR',
       'INSUFFICIENT_DEMAND', 'OTHER_REASONS', 'RAW_MATERIAL_%',
       'SKILLED_LABOUR_%', 'SEMI_AND_UNSKILLED LABOUR_%',
       'INSUFFICIENT_DEMAND_%', 'OTHER_REASONS_%'],
      dtype='object')

In [69]:
stats = new_data.iloc[:, [0,1,2,3,4]]
stats

,INDUSTRY,QUARTER,YEAR,UTILISATION,UNDER_UTILISATION
0,Food and food products,4,2003,79.4,20.6
1,Food and food products,1,2004,79.5,20.5
2,Food and food products,2,2004,80.5,19.5
3,Food and food products,3,2004,81.2,18.8
4,Food and food products,4,2004,83.4,16.6
...,...,...,...,...,...
2039,Furniture and other manufacturing industries,4,2020,66.2,33.8
2040,Furniture and other manufacturing industries,1,2021,74.6,25.4
2041,Furniture and other manufacturing industries,2,2021,77.2,22.8
2042,Furniture and other manufacturing industries,3,2021,82.7,17.3
2043,Furniture and other manufacturing industries,4,2021,81.7,18.3

In [70]:
under = new_data.iloc[:,[0,1,2,10,11,12,13,14]]
under

,INDUSTRY,QUARTER,YEAR,RAW_MATERIAL_%,SKILLED_LABOUR_%,SEMI_AND_UNSKILLED LABOUR_%,INSUFFICIENT_DEMAND_%,OTHER_REASONS_%
0,Food and food products,4,2003,16.990291,5.825243,0.485437,64.077670,12.621359
1,Food and food products,1,2004,22.439024,6.341463,0.487805,57.560976,13.170732
2,Food and food products,2,2004,20.000000,6.153846,0.512821,61.538462,11.794872
3,Food and food products,3,2004,17.553191,7.446809,2.127660,62.234043,10.638298
4,Food and food products,4,2004,11.445783,4.819277,5.421687,69.277108,9.036145
...,...,...,...,...,...,...,...,...
2039,Furniture and other manufacturing industries,4,2020,17.751479,2.071006,0.591716,61.538462,18.047337
2040,Furniture and other manufacturing industries,1,2021,9.055118,3.149606,2.362205,77.165354,8.267717
2041,Furniture and other manufacturing industries,2,2021,9.649123,1.754386,2.631579,75.000000,10.964912
2042,Furniture and other manufacturing industries,3,2021,12.138728,2.312139,1.156069,63.005780,21.387283
2043,Furniture and other manufacturing industries,4,2021,8.743169,2.185792,2.732240,67.759563,18.579235

In [73]:
uu = under.iloc[:, [3,4,5,6,7]].round(2)

In [72]:
under

,INDUSTRY,QUARTER,YEAR,RAW_MATERIAL_%,SKILLED_LABOUR_%,SEMI_AND_UNSKILLED LABOUR_%,INSUFFICIENT_DEMAND_%,OTHER_REASONS_%
0,Food and food products,4,2003,16.990291,5.825243,0.485437,64.077670,12.621359
1,Food and food products,1,2004,22.439024,6.341463,0.487805,57.560976,13.170732
2,Food and food products,2,2004,20.000000,6.153846,0.512821,61.538462,11.794872
3,Food and food products,3,2004,17.553191,7.446809,2.127660,62.234043,10.638298
4,Food and food products,4,2004,11.445783,4.819277,5.421687,69.277108,9.036145
...,...,...,...,...,...,...,...,...
2039,Furniture and other manufacturing industries,4,2020,17.751479,2.071006,0.591716,61.538462,18.047337
2040,Furniture and other manufacturing industries,1,2021,9.055118,3.149606,2.362205,77.165354,8.267717
2041,Furniture and other manufacturing industries,2,2021,9.649123,1.754386,2.631579,75.000000,10.964912
2042,Furniture and other manufacturing industries,3,2021,12.138728,2.312139,1.156069,63.005780,21.387283
2043,Furniture and other manufacturing industries,4,2021,8.743169,2.185792,2.732240,67.759563,18.579235

In [74]:
uu['INDUSTRY'] = under['INDUSTRY']
uu['QUARTER'] = under['QUARTER']
uu['YEAR'] = under['YEAR']
uu

,RAW_MATERIAL_%,SKILLED_LABOUR_%,SEMI_AND_UNSKILLED LABOUR_%,INSUFFICIENT_DEMAND_%,OTHER_REASONS_%,INDUSTRY,QUARTER,YEAR
0,16.99,5.83,0.49,64.08,12.62,Food and food products,4,2003
1,22.44,6.34,0.49,57.56,13.17,Food and food products,1,2004
2,20.00,6.15,0.51,61.54,11.79,Food and food products,2,2004
3,17.55,7.45,2.13,62.23,10.64,Food and food products,3,2004
4,11.45,4.82,5.42,69.28,9.04,Food and food products,4,2004
...,...,...,...,...,...,...,...,...
2039,17.75,2.07,0.59,61.54,18.05,Furniture and other manufacturing industries,4,2020
2040,9.06,3.15,2.36,77.17,8.27,Furniture and other manufacturing industries,1,2021
2041,9.65,1.75,2.63,75.00,10.96,Furniture and other manufacturing industries,2,2021
2042,12.14,2.31,1.16,63.01,21.39,Furniture and other manufacturing industries,3,2021
2043,8.74,2.19,2.73,67.76,18.58,Furniture and other manufacturing industries,4,2021

In [75]:
updated = uu.iloc[:, [5,6,7,0,1,2,3,4]]
updated

,INDUSTRY,QUARTER,YEAR,RAW_MATERIAL_%,SKILLED_LABOUR_%,SEMI_AND_UNSKILLED LABOUR_%,INSUFFICIENT_DEMAND_%,OTHER_REASONS_%
0,Food and food products,4,2003,16.99,5.83,0.49,64.08,12.62
1,Food and food products,1,2004,22.44,6.34,0.49,57.56,13.17
2,Food and food products,2,2004,20.00,6.15,0.51,61.54,11.79
3,Food and food products,3,2004,17.55,7.45,2.13,62.23,10.64
4,Food and food products,4,2004,11.45,4.82,5.42,69.28,9.04
...,...,...,...,...,...,...,...,...
2039,Furniture and other manufacturing industries,4,2020,17.75,2.07,0.59,61.54,18.05
2040,Furniture and other manufacturing industries,1,2021,9.06,3.15,2.36,77.17,8.27
2041,Furniture and other manufacturing industries,2,2021,9.65,1.75,2.63,75.00,10.96
2042,Furniture and other manufacturing industries,3,2021,12.14,2.31,1.16,63.01,21.39
2043,Furniture and other manufacturing industries,4,2021,8.74,2.19,2.73,67.76,18.58

In [76]:
stats.to_csv('MANUFACTURING_STATS.csv', index=False)
updated.to_csv('MANUFACTURING_UNDER.csv', index=False)